name: BET ValueBot

on:
  workflow_dispatch: {}
  schedule:
    # L–V: 10:00 Madrid (CEST = UTC+2 -> 08:00 UTC)
    - cron: "0 8 * * 1-5"
    # S–D: 11:00 y 17:00 Madrid (CEST = UTC+2 -> 09:00 y 15:00 UTC)
    - cron: "0 9,15 * * 6,0"

concurrency:
  group: betbot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests python-dotenv pandas tzdata
          fi

      - name: Run bot
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save CSV (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valuebets_csv
          path: valuebets_resultados.csv
          if-no-files-found: ignore
          retention-days: 1