name: BET ValueBot

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7-10 * * 1-5"        # L–V: 09–12 CEST (una vez por hora)  [UTC+2 -> 07–10 UTC]
    - cron: "0 11-13 * * 1-5"       # L–V: 13–15 CEST (una vez por hora)  [UTC+2 -> 11–13 UTC]
    - cron: "0,30 14-18 * * 1-5"    # L–V: 16–20 CEST, cada 30 min        [UTC+2 -> 14–18 UTC]
    - cron: "*/15 7-18 * * 6,0"     # S–D: 09–20 CEST, cada 15 min        [UTC+2 -> 07–18 UTC]

concurrency:
  group: betbot
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests python-dotenv pandas tzdata
          fi

      - name: Run bot
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Save CSV (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valuebets_csv
          path: valuebets_resultados.csv
          if-no-files-found: ignore
          retention-days: 1